{
 "title": "WebApp by Deployment",
 "tags": [
  "App",
  "Kubernetes"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "deploy",
    "query": {
     "query": "label_values({namespace=\"$namespace\"},deployment)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values({namespace=\"$namespace\", pod=~\"$deploy.*\", container!=\"POD\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Hpa Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of replicas",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kube_deployment_spec_replicas{namespace=~\"$namespace\",deployment=~\"$deploy\"}",
       "legendFormat": "Current"
      },
      {
       "expr": "kube_horizontalpodautoscaler_spec_min_replicas{namespace=~\"$namespace\",horizontalpodautoscaler=~\"$deploy-autoscaler\"}",
       "legendFormat": "HPA min"
      },
      {
       "expr": "kube_horizontalpodautoscaler_spec_max_replicas{namespace=~\"$namespace\",horizontalpodautoscaler=~\"$deploy-autoscaler\"}",
       "legendFormat": "HPA Max"
      },
      {
       "expr": "kube_horizontalpodautoscaler_status_desired_replicas{namespace=~\"$namespace\",horizontalpodautoscaler=~\"$deploy-autoscaler\"}",
       "legendFormat": "desired"
      }
     ]
    },
    {
     "title": "Number of pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_ready{namespace=~\"$namespace\",pod=~\"$deploy-deployment.*|$deploy-[0-9]\"})",
       "legendFormat": "${deploy} Ready"
      },
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\",pod=~\"$deploy-deployment.*|$deploy-[0-9]\"})",
       "legendFormat": "${deploy} Running"
      },
      {
       "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\",pod=~\"$deploy-deployment.*|$deploy-[0-9]\"})",
       "legendFormat": "${deploy} Terminated"
      },
      {
       "expr": "sum by (reason) (kube_pod_container_status_terminated_reason{namespace=~\"$namespace\",pod=~\"$deploy-deployment.*|$deploy-[0-9]\"})",
       "legendFormat": "${deploy} Terminated {{reason}}"
      }
     ]
    }
   ]
  },
  { "title": "HTTP Code", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Number of 2XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{host=~\"$deploy.*|www.$deploy.*\", status=~\"2.*\", exported_namespace=\"$namespace\"}[30s]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Number of 5XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{host=~\"$deploy.*|www.$deploy.*\", status=~\"5.*\", exported_namespace=\"$namespace\"}[30s]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Number of 4XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{host=~\"$deploy.*|www.$deploy.*\", status=~\"4.*\", exported_namespace=\"$namespace\" }[30s]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Number of 3XX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{host=~\"$deploy.*|www.$deploy.*\", status=~\"3.*\", exported_namespace=\"$namespace\"}[30s]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "HTTP 4XX Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{host=~\"$deploy.*|www.$deploy.*\", status=~\"4.*\", exported_namespace=\"$namespace\"}[30s])) / sum(rate(nginx_ingress_controller_requests{host=~\"$deploy.*|www.$deploy.*\", status=~\".*\", exported_namespace=\"$namespace\"}[30s])) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 5XX Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{host=~\"$deploy.*|www.$deploy.*\", status=~\"5.*\", exported_namespace=\"$namespace\"}[30s]))/ sum(rate(nginx_ingress_controller_requests{host=~\"$deploy.*|www.$deploy.*\", status=~\".*\", exported_namespace=\"$namespace\"}[30s])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Ram Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{pod=~\"$deploy.*\", namespace=~\"$namespace\",resource=\"memory\",container=~\"$container\"}",
     "legendFormat": "Requests {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"$deploy.*\", namespace=~\"$namespace\",resource=\"memory\",container=~\"$container\"}",
     "legendFormat": "Limits {{ container }}"
    },
    {
     "expr": "container_memory_working_set_bytes{namespace=~\"$namespace.*\",pod=~\"$deploy.*\",container!=\"\",container=~\"$container\"}",
     "legendFormat": "Conso {{ container }}"
    }
   ]
  },
  {
   "title": "CPU Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{pod=~\"$deploy.*\", namespace=~\"$namespace\",resource=\"cpu\",container=~\"$container\"}",
     "legendFormat": "Requests {{ container }}"
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"$deploy.*\", namespace=~\"$namespace\",resource=\"cpu\",container=~\"$container\"}",
     "legendFormat": "Limits {{ container }}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", pod=~\"$deploy.*\",container!~\"\",container=~\"$container\"}[2m])",
     "legendFormat": "Conso {{ container }}"
    }
   ]
  },
  {
   "title": "CPU Additionnel Necessaire",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_seconds_total{pod=~\"$deploy.*\",namespace=~\"$namespace\",container!~\"\",container=~\"$container\"}[10m])\r\n",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pourcentage de Throttle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{pod=~\"$deploy.*\",namespace=~\"$namespace\",container!~\"\",container=~\"$container\"}[3m]) / rate(container_cpu_cfs_periods_total{pod=~\"$deploy.*\",namespace=~\"$namespace\",container!~\"\",container=~\"$container\"}[3m]) *100",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}